version: '3.8'

services:
  # 1. Database MySQL
  bookland-db:
    image: mysql:8.0
    container_name: bookland-db
    restart: always
    environment:
      MYSQL_DATABASE: bookland_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Redis
  bookland-redis:
    image: redis:7-alpine
    container_name: bookland-redis
    restart: always
    ports:
      - "6379:6379"

  # 3. Backend Spring Boot
  bookland-be:
    build: 
      context: ./BookLand_BE
      dockerfile: Dockerfile
    container_name: bookland-be
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      bookland-redis:
        condition: service_started
      bookland-db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - REDIS_HOST=bookland-redis
      - REDIS_PORT=6379
      - DB_URL=jdbc:mysql://bookland-db:3306/bookland_db?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh
      - DB_USERNAME=root
      - DB_PASSWORD=root
    env_file:
      - ./BookLand_BE/.env.production

volumes:
  mysql_data:
